name: scenicplus-grn
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.19
  - pip=25.3
  - git=2.49.0
  - make=4.4.1
  - bzip2=1.0.8
  - compilers=1.11.0
  - rust=1.96.0
  - maturin=1.13.3
  - wheel=0.47.0
  - setuptools=80.10.2
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.14.1
  - scikit-learn=1.7.2
  - matplotlib-base=3.6.3
  - seaborn=0.13.2
  - macs2=2.2.9.1
  - bedtools=2.31.1
  - samtools=1.23.1
  - htslib=1.23.1
  - pybedtools=0.12.0
  - pybigwig=0.3.22
  - pysam=0.22.1
  - pyranges=0.0.127
  - pyarrow=14.0.2
  - polars=1.35.2
  - ray-default=2.9.3
  - scanpy=1.10.4
  - anndata=0.10.8
  - mudata=0.2.3
  - adjusttext=1.4.0
  - python-annoy=1.17.3
  - bbknn=1.6.0
  - pyscenic=0.12.1
  - ctxcore=0.2.0
  - arboreto=0.1.6
  - dask=2023.4.1
  - distributed=2023.4.1
  - snakemake=7.32.4
  - flatbuffers=25.9.23
  - python-flatbuffers=25.9.23
  - tornado=6.5.2
  - loompy=3.0.8
  - pybiomart=0.2.0
  - cython=3.2.5
  - ipython=8.37.0
  - ipykernel=7.3.0
  - gensim=4.4.0
  - harmonypy=0.2.0
  - leidenalg=0.10.2
  - python-igraph=0.11.8
  - python-levenshtein=0.27.3
  - lxml=5.3.1
  - scanorama=1.7.4
  - scrublet=0.2.3
  - pytables=3.9.2
  - tmtoolkit=0.12.0
  - beautifulsoup4=4.15.0
  - bs4=4.15.0
  - xlrd=1.2.0
  - papermill=2.7.0
  - pygam=0.9.0
  - gseapy=1.2.1
  - bokeh=3.9.1
  - cmake
  - pkg-config
  - libuv
  - xz=5.8.3
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - r-base=4.4.3
  - r-biocmanager=1.30.27
  - r-remotes=2.5.0
  - r-rcppdist=0.1.1
  - bioconductor-genomicranges
  - bioconductor-geneoverlap
  - bioconductor-ucell
  - bioconductor-impute
  - bioconductor-preprocesscore
  - r-fs
  - r-sass
  - r-bslib
  - r-rmarkdown
  - r-htmlwidgets
  - r-htmltable
  - r-hmisc
  - r-dynamictreecut
  - r-fastcluster
  - r-foreach
  - r-doparallel
  - r-iterators
  - r-formula
  - r-checkmate
  - r-wgcna=1.74=r44h40dc89f_0
  - r-seurat=5.5.0
  - r-seuratobject=5.4.0
  - r-signac=1.16.0=r44he56ddfa_0
  - r-igraph=2.1.4=r44hadbbdbc_1
  - r-systemfonts=1.3.2
  - r-tweenr=2.0.3
  - r-writexls=6.8.0
  - r-rjson=0.2.23
  - r-rhpcblasctl=0.23_42
  - r-graphlayouts=1.2.3
  - r-tidygraph=1.3.0
  - r-ggforce=0.5.0
  - r-proxy=0.4_29
  - r-tester=0.3.0
  - r-enrichr=3.4
  - r-harmony=2.0.2
  - r-ggraph=2.2.2
